[package]
name = "aig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aiger = { git = "https://github.com/gipsyh/aiger-rust.git" }
logic-form = { path = "../logic-form" }